version: '3.8'

services:
  api:
    container_name: process-api-habits
    build:
      context: ./services/process-api-habits
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./services/process-api-habits:/app
    environment:
      - SUPABASE_URL=http://host.docker.internal:54321
      - SUPABASE_KEY=${SUPABASE_KEY}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always