version: '3.8'

services:
  api:
    container_name: process-api-habits
    build:
      context: ./services/process-api-habits
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    # volumes:
    #   - ./services/process-api-habits:/app
    volumes:
      - habit_data:/data
    environment:
      - DATABASE_URL=sqlite:////data/adaptive_habits.db 
      - ALLOWED_ORIGINS=http://localhost:3000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    

  webapp:
    container_name: adaptive-habits-web-app
    build:
      context: ./clients/adaptive-habits-web-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - INTERNAL_API_URL=http://process-api-habits:8000/api/v1
    restart: always

volumes:
  habit_data:
  