version: '3.8'

services:
  api:
    container_name: process-api-habits
    build:
      context: ./services/process-api-habits
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./services/process-api-habits:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
